notBool:
    rgpd: rgpd conformite
    customers: qui clientele
    hostingCountry: pays hebergement
    creationDate: date creation
    subscriptionCost: abonnement
    traingCost: cout formation
    webSite: site web

Booleans:
    softOutbound:
        isEmail: mail
        isSms: sms
        isPopin: popin
        isMailPostal: courrier postal
        isCallcenter: centre appel
        isPushMobile: notification push mobile
        isApi: appel api
    softCommSupport:
        isLandingPage: page atterrissage
        isForm: formulaire
        isTracking: code suivi
        isLiveChat: live chat
    softLeadsOperation:
        isContactObject: objet contact
        isCompanyObject: objet societe
        isDefinedFields: champs personnalises
        isIllimitedFields: champs illimite
        isImportCsv: import csv
        isAutoDuplicate: duplication automatique
        isLeadStages: lead stages
    softSegmentCreation:
        isSegmentcreation: creation segment
        isIntelligentSegment: creation segment intelligent
    softMarketingCampaign:
        isAutoResponder: auto répondeur
        isLeadScoring: lead scoring
        isCreationCampaign: creation campagnes
        isDripMarketingCampaign: campagnes drip marketing
        isDragAndDrop: editeur drag drop
    softSocialMedia:
        isTwitterMonitoring: twitter veille
        isTwitterAutoPublication: publication automatique twitter
        isFacebookMonitoring: veille facebook
        isFacebookAutoPublication: publication automatique facebook
        isLinkedinMonitoring: veille linkedin
        isLinkedinAutoPublication: publication automatique linkedin
        isInstagramMonitoring: veille instagram
        isInstagramAutoPublication: publication automatique instagram
    softReport:
        isActivityReportcreation: creation rapport activites
        isActivityReportPeriodicSend: envoi periodique rapport
    softSupport:
        isEmailSupport: support email mail
        isPhoneSupport: support telephone
        isChatSupport: support chat ligne
        isKnowledgeBase: base connaissance
        isTechnicalDocument: documentation technique
    softOtherFunctionnalities:
        isProviderEmailChoice: choix provider email
        isBlogEdition: edition blog
        isTouchPad: tablette touchpad magasin
        isSmtpRelay: smtp relais email transactionnel
        isRssToEmail: rss email flux

EmptyWords:
    allô
    aucuns
    auriez
    auxdits
    aviez
    ayons
    bof
    çà
    certaines
    chez
    comment
    da
    desquels
    deviez
    devras
    doit
    dues
    dût
    es
    êtes
    eurêka
    excepté
    fouchtra
    fûmes
    ho
    hurrah
    laquelle
    leur
    mazette
    mâtin
    ne
    nulle
    or
    outre
    pas
    plein
    pourraient
    pourvu
    pouviez
    puis
    pussent
    que
    quoi
    saperlipopette
    serait
    sien
    sommes
    ta
    telles
    touchant
    une
    veuillez
    voilà
    voudrez
    voulante
    voulue
    vôtre
    afin
    assez
    alors
    auquel
    aurions
    auxquelles
    avions
    aïe
    boum
    car
    certains
    chic
    concernant
    dans
    devaient
    devions
    devrez
    doive
    duquel
    eh
    et
    étiez
    eus
    eûmes
    furent
    fût
    holà
    hé
    le
    leurs
    me
    miséricorde
    ni
    nulles
    ôté
    palsambleu
    patatras
    plouf
    pourrais
    pouvaient
    pouvions
    puisque
    put
    quel
    quoique
    sapristi
    seras
    sienne
    son
    tandis
    tels
    tous
    unième
    veuillons
    vos
    voudriez
    voulantes
    voulues
    vôtres
    ah
    apr
    aura
    aurons
    auxquels
    avoir
    bah
    bravissimo
    ce
    ces
    chiche
    contre
    de
    devais
    devoir
    devriez
    doivent
    durant
    elle
    étaient
    étions
    eusse
    eût
    fus
    fûtes
    hop
    il
    ledit
    lorsque
    merci
    moi
    nonobstant
    nuls
    ou
    pan
    pechère
    plus
    pourrait
    pouvais
    pouvoir
    puisse
    pécaïre
    quelle
    rataplan
    sauf
    serez
    siennes
    sont
    tant
    tes
    tout
    unièmes
    veulent
    votre
    voudrions
    voulants
    voulurent
    zut
    ai
    as
    aurai
    auront
    avaient
    avons
    basta
    bravo
    ceci
    cet
    chouette
    corbleu
    debout
    devait
    devons
    devrions
    doives
    durent
    elles
    étais
    être
    eussent
    eûtes
    fusse
    grâce
    hormis
    ils
    lequel
    lui
    merde
    moins
    nos
    où
    par
    pendant
    plusieurs
    pourras
    pouvait
    pouvons
    puissent
    pût
    quelles
    revoici
    se
    seriez
    siens
    sous
    taratata
    tien
    toute
    v'lan
    veut
    voudra
    voudrons
    voulez
    voulus
    aie
    attendu
    auraient
    autant
    avais
    ayant
    beaucoup
    cela
    cette
    chut
    coucou
    depuis
    devant
    devra
    devrons
    donc
    dus
    en
    était
    eu
    eusses
    évohé
    fussent
    ha
    hors
    jarnicoton
    les
    là
    mes
    mon
    notre
    oh
    ouais
    parbleu
    peu
    pouah
    pourrez
    pouvant
    psitt
    puisses
    qq
    revoilà
    selon
    serions
    sinon
    soyez
    tayaut
    tienne
    toutes
    va
    veux
    voudrai
    voudront
    vouliez
    voulussent
    aient
    au
    aurais
    autre
    avait
    ayante
    bernique
    aura
    celle
    ceux
    ciao
    couic
    des
    devante
    devrai
    devront
    dont
    dussent
    encontre
    étant
    eue
    eussiez
    évoé
    fusses
    hein
    hou
    je
    lesdites
    ma
    mien
    morbleu
    nôtre
    ohé
    ouf
    parce
    peuchère
    pour
    pourriez
    pouvante
    pst
    puissiez
    qqch.
    quelqu
    rien
    sera
    serons
    soi
    soyons
    taïaut
    tiennes
    tu
    vers
    via
    voudraient
    voulaient
    voulions
    voulut
    aies
    aucun
    aurait
    autres
    avant
    ayantes
    bien
    aurait
    celles
    chacun
    clic
    crac
    desdites
    devantes
    devraient
    dia
    du
    dut
    endéans
    étante
    eues
    eussions
    fi
    fussiez
    hem
    hourra
    jusque
    lesdits
    made
    mienne
    motus
    nôtres
    olé
    ouille
    pardi
    peut
    pourquoi
    pourrions
    pouvantes
    pu
    puissions
    qqn
    quels
    sa
    serai
    seront
    soient
    stop
    te
    tiens
    tudieu
    veuille
    vivement
    voudrais
    voulais
    vouloir
    voulût
    ait
    aucune
    auras
    aux
    avec
    ayants
    bigre
    avait
    celui
    chacune
    clac
    cric
    desdits
    devants
    devrais
    diantre
    dudit
    dès
    entre
    étantes
    euh
    eut
    fichtre
    fussions
    hep
    hue
    la
    lesquelles
    mais
    miennes
    moyennant
    nous
    on
    oust
    pardieu
    peuvent
    pourra
    pourrons
    pouvants
    pue
    purent
    quand
    qui
    sacristi
    seraient
    ses
    sois
    suis
    tel
    toi
    turlututu
    veuillent
    vlan
    voudrait
    voulait
    voulons
    vous
    aucunes
    aurez
    auxdites
    avez
    ayez
    bis
    ça
    cependant
    chaque
    comme
    crénom
    desquelles
    devez
    devrait
    dois
    due
    dû
    envers
    étants
    eurent
    eux
    fors
    fut
    heu
    hum
    ladite
    lesquels
    malgré
    miens
    na
    nul
    ont
    ouste
    parmi
    peux
    pourrai
    pourront
    pouvez
    pues
    pus
    quant
    quiconque
    sans
    serais
    si
    soit
    sur
    telle
    ton
    un
    veuilles
    voici
    voudras
    voulant
    voulu
    vu